# Instalando Bibliotecas

In [ ]:
pip install --upgrade google-cloud-bigquery[pandas]

In [ ]:
pip install --upgrade google-cloud

In [ ]:
pip install --upgrade google-cloud-storage

In [ ]:
pip install --upgrade pandas-gbq

# Importando Bibliotecas

In [43]:
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account

# 4. Utilizando consultas SQL responda as perguntas

In [44]:
credentials = service_account.Credentials.from_service_account_file('svc-data-engineer-test.json', scopes =["https://www.googleapis.com/auth/cloud-platform"])

# 4.1 - Quantos usuários temos por estado de acesso ordenando pelo estado com maior número (coluna address_state)?

In [45]:
query = '''SELECT DISTINCT address_state, COUNT(*) AS users_by_state FROM (select cpf, address_state FROM `begrowth-user-api-demo.bg_users.bg_data_enginner_test_aisllan_max_caldeira`)  GROUP BY address_state ORDER BY users_by_state DESC'''

In [46]:
pd.read_gbq(credentials=credentials, query=query)

          address_state  users_by_state
0             Sao Paulo             446
1          Minas Gerais             302
2     Rio Grande do Sul             170
3                 Bahia             150
4                Parana             140
5        Santa Catarina             118
6            Pernambuco              96
7        Rio de Janeiro              74
8                 Goias              64
9               Paraiba              60
10             Maranhao              56
11             Amazonas              48
12                Ceara              46
13       Espirito Santo              46
14              Sergipe              38
15             Rondonia              34
16                Piaui              30
17   Mato Grosso do Sul              30
18  Rio Grande do Norte              28
19                 Para              22
20          Mato Grosso              22
21              Alagoas              12
22            Tocantins               4
23                 Acre               2
24              Roraima               2

# 4.2 - Quantos usuários únicos temos por estado de acesso ordenando pelo estado com maior número (coluna address_state)?

In [47]:
query = '''SELECT DISTINCT address_state, COUNT(*) AS unique_users_by_state FROM (select distinct cpf, address_state FROM `begrowth-user-api-demo.bg_users.bg_data_enginner_test_aisllan_max_caldeira`)  GROUP BY address_state ORDER BY unique_users_by_state DESC'''

In [48]:
pd.read_gbq(credentials=credentials, query=query)

          address_state  unique_users_by_state
0             Sao Paulo                    216
1          Minas Gerais                    149
2     Rio Grande do Sul                     81
3                 Bahia                     75
4                Parana                     70
5        Santa Catarina                     57
6            Pernambuco                     48
7        Rio de Janeiro                     37
8                 Goias                     31
9              Maranhao                     28
10              Paraiba                     27
11             Amazonas                     24
12                Ceara                     23
13       Espirito Santo                     23
14              Sergipe                     19
15             Rondonia                     17
16                Piaui                     15
17   Mato Grosso do Sul                     15
18  Rio Grande do Norte                     14
19          Mato Grosso                     11
20                 Para                     10
21              Alagoas                      6
22            Tocantins                      2
23                 Acre                      1
24              Roraima                      1

# 4.3 - Quantos usuários temos por source ordando por ordem alfabética?

In [49]:
query = '''SELECT utm_source, COUNT(*) AS users_by_source FROM `begrowth-user-api-demo.bg_users.bg_data_enginner_test_aisllan_max_caldeira` GROUP BY utm_source ORDER BY utm_source ASC'''

In [50]:
pd.read_gbq(credentials=credentials, query=query)

  utm_source  users_by_source
0   Facebook              656
1     Google             1052
2   WhatsApp              332

# 4.4 - Quantos usuários únicos temos por source ordando por ordem alfabética?

In [51]:
query = '''SELECT DISTINCT utm_source, COUNT(*) AS unique_users_by_source FROM (select distinct cpf, utm_source FROM `begrowth-user-api-demo.bg_users.bg_data_enginner_test_aisllan_max_caldeira`)  GROUP BY utm_source ORDER BY utm_source ASC'''

In [52]:
pd.read_gbq(credentials=credentials, query=query)

  utm_source  unique_users_by_source
0   Facebook                     320
1     Google                     517
2   WhatsApp                     163

# 4.5 - Sabendo disso, nosso time precisa saber qual a Região Fiscal que esse CPF foi registrado:

In [53]:
query = '''SELECT C.uf As fiscal_region, D.*  FROM `begrowth-user-api-demo.bg_users.bg_data_enginner_test_aisllan_max_caldeira` D
INNER JOIN  `begrowth-user-api-demo.bg_users.cpf_state` C
              ON SUBSTR((CAST(D.cpf as string)), -3, 1) = CAST(C.id as string)'''

In [54]:
pd.read_gbq(credentials=credentials, query=query)

,fiscal_region,id,first_name,last_name,email,gender,address,address_state,utm,utm_country,utm_source,utm_vertical,cpf,dt_insert,candidate_name
0,"ES, RJ",392,Romain,Molnar,rmolnarav@qq.com,Male,"{'geo_latitude': -8.1754307, 'geo_longitude': ...",Acre,br-fb-cc,Brasil,Facebook,Cartão de Crédito,52007159708,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira
1,"ES, RJ",91,Ara,Carrabot,acarrabot2i@wordpress.org,Female,"{'geo_latitude': -0.9254064, 'geo_longitude': ...",Para,br-gg-cc,Brasil,Google,Cartão de Crédito,3702171797,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira
2,"ES, RJ",91,Ara,Carrabot,acarrabot2i@wordpress.org,Female,"{'geo_latitude': -0.9254064, 'geo_longitude': ...",Para,br-gg-cc,Brasil,Google,Cartão de Crédito,3702171797,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira
3,"ES, RJ",67,Giusto,Corain,gcorain1u@google.com.hk,Male,"{'geo_latitude': -1.2936976, 'geo_longitude': ...",Para,br-gg-emp,Brasil,Google,Empréstimo,25903259758,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira
4,"ES, RJ",141,Benedick,Flode,bflode3w@rediff.com,Male,"{'geo_latitude': -13.5362103, 'geo_longitude':...",Bahia,br-fb-cc,Brasil,Facebook,Cartão de Crédito,48643035769,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,"DF, GO, MS, MT, TO",743,Dene,Carson,dcarsonkm@wisc.edu,Male,"{'geo_latitude': -28.3276327, 'geo_longitude':...",Rio Grande do Sul,br-wpp-fin,Brasil,WhatsApp,Financiamento,19129600103,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira
2036,"DF, GO, MS, MT, TO",94,Thaine,Nazair,tnazair2l@is.gd,Male,"{'geo_latitude': -19.1097385, 'geo_longitude':...",Mato Grosso do Sul,br-gg-cc,Brasil,Google,Cartão de Crédito,2976929173,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira
2037,"DF, GO, MS, MT, TO",567,Zelma,Moth,zmothfq@globo.com,Female,"{'geo_latitude': -21.9111483, 'geo_longitude':...",Mato Grosso do Sul,br-fb-emp,Brasil,Facebook,Empréstimo,26822583106,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira
2038,"DF, GO, MS, MT, TO",711,Hercule,Sagrott,hsagrottjq@tiny.cc,Male,"{'geo_latitude': -6.0777029, 'geo_longitude': ...",Rio Grande do Norte,br-fb-cc,Brasil,Facebook,Cartão de Crédito,47211263105,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira
2039,"DF, GO, MS, MT, TO",48,Merv,Tull,mtull1b@cmu.edu,Male,"{'geo_latitude': -6.4525359, 'geo_longitude': ...",Rio Grande do Norte,br-gg-emp,Brasil,Google,Empréstimo,43064795104,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira

# 4.6 - O estado de acesso obtido atraves das coordenadas geograficas fica na mesma Região Fiscal que esse CPF foi registrado? (Criar flag same_state no select)

In [55]:
query = '''WITH A AS (SELECT C.uf As fiscal_region, D.address_state, D.* EXCEPT(address_state) FROM `begrowth-user-api-demo.bg_users.bg_data_enginner_test_aisllan_max_caldeira` D
LEFT JOIN  `begrowth-user-api-demo.bg_users.cpf_state` C
              ON SUBSTR((CAST(D.cpf as string)), -3, 1) = CAST(C.id as string)),
B AS (SELECT B.uf, initials FROM `begrowth-user-api-demo.bg_users.brazilian_state` B
LEFT JOIN `begrowth-user-api-demo.bg_users.cpf_state` C
  ON B.initials LIKE CONCAT ('%', C.uf, '%')
              OR C.uf LIKE CONCAT ('%', B.initials, '%'))

SELECT IF((B.initials LIKE CONCAT ('%', A.fiscal_region, '%') OR A.fiscal_region LIKE CONCAT ('%', B.initials, '%')), TRUE, FALSE) AS same_state, * EXCEPT(uf, initials) FROM A
LEFT JOIN B
  ON A.address_state = B.uf'''

In [56]:
pd.read_gbq(credentials=credentials, query=query)

,same_state,fiscal_region,address_state,id,first_name,last_name,email,gender,address,utm,utm_country,utm_source,utm_vertical,cpf,dt_insert,candidate_name
0,False,"ES, RJ",Acre,392,Romain,Molnar,rmolnarav@qq.com,Male,"{'geo_latitude': -8.1754307, 'geo_longitude': ...",br-fb-cc,Brasil,Facebook,Cartão de Crédito,52007159708,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira
1,False,MG,Para,107,Yoko,Antonutti,yantonutti2y@loc.gov,Female,"{'geo_latitude': -1.8409583, 'geo_longitude': ...",br-fb-cc,Brasil,Facebook,Cartão de Crédito,89000458650,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira
2,True,"AC, AM, AP, PA, RO, RR",Para,798,Ame,Adan,aadanm5@phpbb.com,Female,"{'geo_latitude': -0.8667864, 'geo_longitude': ...",br-fb-cc,Brasil,Facebook,Cartão de Crédito,54398115242,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira
3,False,"ES, RJ",Para,91,Ara,Carrabot,acarrabot2i@wordpress.org,Female,"{'geo_latitude': -0.9254064, 'geo_longitude': ...",br-gg-cc,Brasil,Google,Cartão de Crédito,3702171797,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira
4,False,"ES, RJ",Para,91,Ara,Carrabot,acarrabot2i@wordpress.org,Female,"{'geo_latitude': -0.9254064, 'geo_longitude': ...",br-gg-cc,Brasil,Google,Cartão de Crédito,3702171797,2022-12-18 22:02:00+00:00,Aisllan Max Caldeira
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,False,"BA, SE",Rio Grande do Norte,24,Zorina,Devanny,zdevannyn@jugem.jp,Female,"{'geo_latitude': -6.6760711, 'geo_longitude': ...",br-fb-emp,Brasil,Facebook,Empréstimo,1544518510,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira
2036,False,"DF, GO, MS, MT, TO",Rio Grande do Norte,48,Merv,Tull,mtull1b@cmu.edu,Male,"{'geo_latitude': -6.4525359, 'geo_longitude': ...",br-gg-emp,Brasil,Google,Empréstimo,43064795104,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira
2037,False,"AC, AM, AP, PA, RO, RR",Rio Grande do Norte,200,Angy,Kingsnoad,akingsnoad5j@cdbaby.com,Female,"{'geo_latitude': -5.98978, 'geo_longitude': -3...",br-gg-emp,Brasil,Google,Empréstimo,17782029260,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira
2038,False,"PR, SC",Rio Grande do Norte,748,Wallace,McCarron,wmccarronkr@va.gov,Male,"{'geo_latitude': -5.1942574, 'geo_longitude': ...",br-gg-fin,Brasil,Google,Financiamento,97875031915,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira
2039,False,MG,Rio Grande do Norte,820,Lizzie,Pittendreigh,lpittendreighmr@etsy.com,Female,"{'geo_latitude': -6.4525359, 'geo_longitude': ...",br-wpp-fin,Brasil,WhatsApp,Financiamento,47309376609,2022-12-16 16:41:00+00:00,Aisllan Max Caldeira